### ISSUE TITLE
Implementation roadmap

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/IterativeSolvers.jl#1]
A comprehensive listing of methods in the references.
Please remove any methods are impractical/obsolete and add methods worth implementing to the list.

Linear systems
- Stationary methods
  - [x] Jacobi (LT)
  - [x] Gauss-Seidel (LT)
  - [x] Successive overrelaxation, SOR (LT)
  - [x] Symmetric SOR (LT)
- Nonstationary methods
  - [x] GMRES (LT, Saa)
  - [x] MINRES (LT)
  - [x] Conjugate Gradients, CG (LT)
  - [x] LSQR
  - [x] LSMR
  - [x] BiCGStab(l) (Sle)
  - [x] Chebyshev iteration (LT)
  - [ ] Quasi-Minimal Residual, QMR (LT)
  - [ ] DQGMRES

(Generalized) eigenproblems
- Without subspace
  - [x] (Shift-and-inverted) power iteration (ET)
  - [ ] Rayleigh Quotient Iteration [1]
- Krylov subspace methods
  - [ ] Implicitly restarted Lanczos (ET)
  - [ ] Implicitly restarted Arnoldi (ET)
- Other subspace methods
  - [ ] Jacobi-Davidson method (ET)
  - [x]  [LOPCG](http://www.mathworks.com/matlabcentral/fileexchange/48-lobpcg-m)
  - [ ] Accelerated Rayleigh Quotient Iteration [1]
  - [ ] (Shift-and-inverted) subspace iteration (ET)

Singular value decomposition
- [x] Golub-Kahan-Lanczos (ET)

References
- LT: [Templates for the Solution of Linear Systems](http://www.netlib.org/linalg/html_templates/report.html)
- ET: [Templates for the Solution of Algebraic Eigenvalue Problems](http://web.eecs.utk.edu/~dongarra/etemplates/book.html)
- Saa: GMRES: A generalized minimal residual algorithm for solving nonsymmetric linear systems [(pdf)](http://www.stat.uchicago.edu/~lekheng/courses/324/saad-schultz.pdf) 
- Sle: BiCGstab(l) and other hybrid Bi-CG methods [(pdf)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.139.7946&rep=rep1&type=pdf)
- TB: [Numerical linear algebra](http://www.worldcat.org/title/numerical-linear-algebra/oclc/36084666)
- HV: [Iterative Krylov methods for large linear systems](http://www.worldcat.org/title/iterative-krylov-methods-for-large-linear-systems/oclc/837021440)

[1] Low-priority methods: they are quite expensive per iteration.

**Comment by thraen** [comment]
I tried the gauss-seidel function of the package as smoother for multigrid. The implementation given doesn't account for sparse matrices and is thus not usable in such contexts (large, sparse).

**Comment by lruthotto** [comment]
@thraen: You might want to look into the function `sor` and other iterative solvers that are optimized for sparse matrices in https://github.com/lruthotto/KrylovMethods.jl. I use the `sor` a lot as a preconditioner and it is reasonably fast. It makes use of the sparse matrix format.

**Comment by thraen** [comment]
Thanks a lot for pointing that out!

**Comment by Sisyphuss** [comment]
Is it worthwhile to add [Aitken's delta-squared process](https://en.wikipedia.org/wiki/Aitken%27s_delta-squared_process) into the list?

**Comment by klkeys** [comment]
I noticed that this package was listed for [Julia GSOC 2016](http://julialang.org/soc/ideas-page.html#native-julia-implementations-of-iterative-solvers-for-numerical-linear-algebra). Mike Innes [suggested](https://groups.google.com/forum/#!topic/julia-users/dfJ0kiHVe1w) that I pipe up here if I wanted to help. Is anybody here able and willing to serve as a mentor?

**Comment by jiahao** [comment]
@klkeys Thanks for your interest. I'd be thrilled to have someone help out with this package!

One of the biggest challenges is to unify the various methods available in similar packages like https://github.com/lruthotto/KrylovMethods.jl and https://github.com/JuliaOptimizers/Krylov.jl. In some sense, this package has been more experimental in nature whereas the other two have been more focused on efficient implementations that work well for practical applications. Now that we (or at least, I) have some experience in writing these algorithms, I'd be very interested to figure out a common API across all the various solvers available.

cc: @lruthotto @dpo

**Comment by lruthotto** [comment]
I'd be glad to help work out a common API and a convergence of the packages in terms of efficiency. I'm not sure how much time I'll have to work on it myself during this summer, but I'd be happy to provide input as much as I can. Please keep me posted if you start a discussion somewhere.

**Comment by dpo** [comment]
I'm very interested in working out a good common API as well. I'm currently quite happy with the API in `Krylov.jl` but I'm of course open to discussing it. It's very unlikely that I'll have free time this summer to mentor though, but I'm happy to participate in discussions when I can.

**Comment by zimoun** [comment]
Will anyone work on [Julia GSOC 2016](http://julialang.org/soc/ideas-page.html#native-julia-implementations-of-iterative-solvers-for-numerical-linear-algebra) ?

It should be nice to have a common API to easily switch between the different implementations or to merge them. For example,

 - the preconditioning scheme is different (e.g., `M(x)` in [KrylovMethods.jl](https://github.com/lruthotto/KrylovMethods.jl) and `M\x` in IterativeSolvers.jl.
 - an abstract layer to manage preconditioners and then implement classic ones (see [there](http://www.mcs.anl.gov/petsc/petsc-current/docs/manual.pdf) e.g., sec. 4.4 Preconditioners and Tab. 4  )
 - write a "bridge" to be able to transparently use [PETSc.jl](https://github.com/JuliaParallel/PETSc.jl), other GSOC 2016.

cc: @cortner [related issue](https://github.com/JuliaOpt/Optim.jl/issues/188) and #71

**Comment by ChrisRackauckas** [comment]
I think MINRES should be added to this list.

**Comment by lruthotto** [comment]
@zimoun: We chose to provide the preconditioner as a function handle that computes the inverse, for example, ```M(x) = M\x ``` to allow as much flexibility to the user as possible. This way you should be able to use routines from PETSc without an issue (you may have to write a wrapper). I'm not sure you need another abstract layer for preconditioners. 

Something we could to in KrylovMethods is to allow ```M``` being a matrix and then building the function. We do something similar for ```A``` already. Do you think that's a good way to go?

@ChrisRackauckas : There is a basic version of minres in KrylovMethods (https://github.com/lruthotto/KrylovMethods.jl/blob/master/src/minres.jl) which might be a good starting point.

**Comment by cortner** [comment]
> I'm not sure you need another abstract layer for preconditioners.

My own perspective: in optimisation you need more than just M(x). You need to provide M * x, M \ x, <x, My>, <x, M\y>. 

But I would argue even in linear algebra you may want to create some abstraction. E.g., is the preconditioner right- or left-preconditioned? Maybe I am overcomplicating it. I do think for `Optim.jl` it will be useful to use dispatch instead of function handles. I won't get too stressed if this is incompatible with `IterativeSolvers.jl`, though it might be a shame.

**Comment by lruthotto** [comment]
I agree that we should distinguish between left and right preconditioners. How about having two variables, for example, ```Mr``` and ```Ml``` doing this? 

Regarding the abstraction issue: Can you give me an example when you need to multiply with the preconditioner?

**Comment by cortner** [comment]
> Regarding the abstraction issue: Can you give me an example when you need to multiply with the preconditioner?

Basically to compute distance, but I only need the inner products for that. So now that you pressure me to think about it, I am not sure whether it was just sloppiness on my part. I will think about it some more, but it is possible that only `M \ x, <x, My>, <x, M \ y>` is needed.

But don't you need `M * x` for right-preconditioning?

**Comment by lruthotto** [comment]
No, you need the inverse for left- and right-preconditioning. See, e.g., Chapter 9 in Saad's book: www-users.cs.umn.edu/~saad/IterMethBook_2ndEd.pdf 

Regarding the inner product: Think, also about when you need that **inside** the linear solver. So far, I haven't seen the necessity and still think that inside the methods you only need ```M\x```.

**Comment by cortner** [comment]
I went through a couple of algorithms that I've used in the past. I now think most can be written (or re-written) without `<x, Mx>` , but I am not sure all of them. Two examples:

1. E.g., the Hager-Zhang nCG needs to compute the length of a step; see `Optim.jl/src/cg.jl`, line 236:  (here, `P = M^{-1}`)
```
        dPd = precondinvdot(s, cg.P, s)
```
Maybe this can be removed, but I don't immediately see how; I can turn it into a recursion, but then I still need it at least once.

2. Another example that comes to mind (this comes up in saddle-search, but very similar context); to project out some "bad directions" `y_j` we add `\sum_{j} <x, y_j>_P^2` to the objective, but this is part of the algorithm, *not* part of the user input.

**Comment by dpo** [comment]
There's an implementation of MINRES in Krylov.jl: https://github.com/JuliaOptimizers/Krylov.jl/blob/develop/src/minres.jl. It supports preconditioning. Only SPD preconditioning makes sense for MINRES, except in very specific cases.

**Comment by zimoun** [comment]
@lruthotto I agree and I think that provide only the matrix-vector product as function is the right direction; as you are explaining and as it is implemented in [KrylovMethods.jl](https://github.com/lruthotto/KrylovMethods.jl). My point is: it is not consistent with the current behavior of [IterativeSolvers.jl see e.g., gmres l.81](https://github.com/JuliaLang/IterativeSolvers.jl/blob/master/src/gmres.jl), which uses `M\x` hard coded. It was the starting point of the discussion #71.
From my point of view, all the operations should be a type in the flavor of [`LinearOperator.jl`](https://github.com/JuliaOptimizers/LinearOperators.jl)

Since we are talking about projection methods, this means relative to an inner product, isn't it ?
(note: I am not sure, but I think `<v, Mv>` and/or `<v, M\v>` are used in some deflated methods ?)

**Comment by cortner** [comment]
@zimoun : why does `M \ x`, which is the same as `\(M, x) not count as a function for you?

**Comment by cortner** [comment]
@lruthotto Just to add to my examples above: it is maybe becoming clear now that for linear algebra you only need `M \ x`, and that any other functionality would be an extension used in other contexts. So I may just leave you in peace here and start a new issue in `Optim.jl`, but try and keep an eye on this.

**Comment by zimoun** [comment]
@cortner I am not sure to understand the question. Maybe I miss a point.
From what I know, `M(x)` eats a vector, does whatever, and then returns a vector. 
If now `M` is a matrix, with nothing more defined, then `M\x` returns the vector solution of `My=x` (by applying LU or QR factorization).

Let consider that I am able to build the matrix `P`, `A` and I would like to solve `P*A*u = P*b`.
 - using `KrylovMethods.jl`, I define `M(x) = P*x` and I feed gmres.
 - using `IterativeSolvers.jl`, I have to play around the type system to define somehow an "object" `M` with the operation `M\x` providing by `P*x`, and then I feed gmres.

From my point of view, it is not consistent (and the behavior of `IterativeSolvers.jl` appears to me confusing, because `\` generally means solve but in this context, it means apply `P`)

**Comment by cortner** [comment]
@zimoun If `M` is an instance of a type `MyPreconditioner`, storing whatever information it needs, then `\\(M, x) = M \ x` can be defined any way you want. So the mapping `x \mapsto M \ x` does just the same: eat a vector and spit out a vector.

**Comment by lruthotto** [comment]
@cortner: Thanks for starting the discussion and for your examples. 

Take a look at https://github.com/lruthotto/KrylovMethods.jl/tree/devPrecond . With just adding a few lines, I was able to accommodate ```M``` as a matrix or a vector (useful for diagonal preconditioners). What do you think about these changes?

**Comment by cortner** [comment]
That is essentially what I have in mind. Two (three) comments:

 * I would not write in the documentation that `M` should be either a function that computes M\\x or a matrix or vector such that M\\x is computed; rather `M` should be of an arbitrary type as long as preconditioner(M, x) can be called, which returns M^{-1} x. (by whatever means).  This doesn't prevent you from keeping the default behaviour you've already implemented for functions, arrays or vectors.  To give you two concrete examples: 
      - if you look at `Optim.jl/cg.jl` you will see that Tim Holy implemented `M^{-1} x` for a diagonal preconditioner by storing `M_ii^{-1}` rather than `M_ii`. By wrapping this into a type, it can then be specified which of these the vector is understood to provide. E.g., one could provide the types `DiagonalPrecon` and `InverseDiagonalPrecon` to take care of this.
      - As @zimoun pointed out, in some cases (BEM?) one actually has the inverse explicitly available, so the matrix being passed might already be the inverse. Again, by wrapping into types one can distinguish.    (that said, I agree with your default behaviour!)

* I would not choose `preconditioner` for the name of the method that applies it, because it sounds to me like you might be constructing the preconditioner. *Personally* I would actually stick with `M \ x`, but I appreciate that this seems to cause confusion. Maybe `precondition`, `applyprecond`, just `precond`, or something like that? Tim Holy called it `precondfwd!`. To be honest, I haven't thought of a really good name.  In the end I am not too fussed about this. 

* I would probably do the default implementation in-place. A wrapper can then be provided to call whatever the user provides, e.g., `precondfwd!(px, M, x) = copy!(px, precondfwd(M, x))`

**Comment by stevengj** [comment]
For [preconditioner (KSP) objects in  PETSc.jl](https://github.com/JuliaParallel/PETSc.jl/blob/master/src/ksp.jl), we provide `A_ldiv_B!` (in-place `M \ x`), which corresponds to how preconditioners are defined in PETSc.   Defining `A_ldiv_B!`  for an object is sufficient to define `\` as well, I believe, and it allows the solver to take advantage of in-place operations if it wants.    So I would recommend this for IterativeSolvers too.

We also provide a function to do `At_ldiv_B!` (in-place `M' \ x`), but currently this is missing from Base.

**Comment by lruthotto** [comment]
@cortner: Thanks for your encouragement and suggestions. I just pushed some changes to the branch and switched more methods over to the new call to ```applyPrecond```. I quite like it: It made the code not much longer and more flexible. Precondioners can now be provided as functions, arrays, and vectors. 

What still remains is the option of left vs. right preconditioning in CG and other methods as well as preconditioning in ```minres``` (which @dpo has already implemented in his package)

**Comment by cortner** [comment]
Personally, I like `applyPrecond`, but I fear that it clashes with Julia naming conventions. Just `applyprecond` or `apply_precond` ok?

Although `A_ldiv_B!` hurts my eyes, this has some advantages: 
* it is in `Base`, which means that if two modules implement it then they can import from `Base` and don't need to know of each other. Btw, this is an issue I never quite wrapped my head around - is this discussed somewhere in depth? Can anybody comment?
* it is widely understood what it means
* you don't need to implement boiler-plate code for the standard operators (even though this is minimal effort)

**Comment by ChrisRackauckas** [comment]
Would an Algebraic Multigrid be considered for this package?

**Comment by cortner** [comment]
I've written a simple wrapper for pyamg which I was hoping to integrate but if you have something better, I'd be very interest d.

**Comment by ViralBShah** [comment]
PyAMG is a pretty solid package.

**Comment by ChrisRackauckas** [comment]
I think we should get a native Julia version, but PyAMG will work really well in the meantime. Good job!

**Comment by cortner** [comment]
Thank you - I'll be happy I can register the package then.

**Comment by lruthotto** [comment]
Talking about native julia implementation of mulitgrid methods. @erantreister has started putting out a package here: https://github.com/JuliaInv/Multigrid.jl 

We're still working on some details, but it'll be in good shape soon. Always open to feedback/suggestions.

**Comment by cortner** [comment]
I am now almost certain that we should use `A_ldiv_B!` or simply `\\` for application of the Preconditioner. If we do not, then we would have to create a `Preconditioning.jl` module that just defines the interface without anything else. This is a real short-coming of the module system, which I believe traits are supposed to fix? But by using `A_ldiv_B!` or `\\` we can simply overload the operators that are in `Base`, so there is no problem anymore. 

I would really appreciate to get this confirmed (or contradicted) by somebody who has a deeper understanding of Julia than I do.

**Comment by andreasnoack** [comment]
I really don't see the point in introducing a new a special linear solve *function* just for preconditioners. Applying the preconditioner is a linear solve and `\`,`A_ldiv_B!` are the functions for linear solves and they can be overloaded. Regarding diagonal preconditioning then we have `Diagonal` in `Base.LinAlg` for that. If some of the abstractions in `Base.LinAlg` are insufficient, then please raise issues.

**Comment by cortner** [comment]
@andreasnoack Thank you - I agree it would be good to stick with this.

**Comment by raminammour** [comment]
Hello all!

First thank you, I am a frequent user/abuser of this package! (I hope this is a good thread for this post)

1- I was wondering if you have any plans to support the LinearMaps.jl package as a general interface, instead of MatrixFcn which tries to accomplish the same, with less options. I have been using LinearMaps instead of MatrixFcn with IterativeSolvers, and for the most part, it works.

2- When the preconditioners are passed as a function (as in gmres for example), it is better to assume that the inverse is passed directly so Pinv*x replaces Pl\x in the code, or have the two options, maybe. For most of the things I do, the linear operators are large scale and beyond building explicitly.

3- I also cannot wait till this package is integrated with different optimization packages to replace all direct solvers. It will open many doors for large scale optimization.

Again, thanks for the developers,
Cheers!

**Comment by syntapy** [comment]
Hey, I'd like to work on this for GSOC 2017 if yalls would be fine with that. I think I'd have fun with it. I'm not sure yet whether I'd be able to do GSOC full time since I have work obligations, but if not, I'd still love to do this part time for free

**Comment by barche** [comment]
From my point of view (as a potential user) I would be interested most in preconditioners (ILU, AMG).

**Comment by erantreister** [comment]
Hi Bart,
I have a package with some multigrid preconditioners in Multigrid.jl. In particular smoothed aggregation AMG. It's a part of the JuliaInv collection of packages.
Cheers,
Eran Treister.

**Comment by barche** [comment]
Aha, good to know, thanks!

**Comment by GregVernon** [comment]
How about the recently developed Alternating Anderson Richardson (AAR) method?

_Alternating Anderson-Richardson method: An efficient alternative to preconditioned Krylov methods for large, sparse linear systems_  https://arxiv.org/pdf/1606.08740.pdf

**Comment by mohamed82008** [comment]
It would be nice to have an updated roadmap in light of the new developments in Julia's iterative solvers ecosystem.

**Comment by Xx-fractale-xX** [comment]
Good idea @mohamed82008.
I recently add some methods in `Krylov.jl` for information, (DQGMRES, DIOM, USYMLQ, USYMQR, TFQMR, FOM) with allocations tests too.
If some methods are relevant for `IterativeSolvers.jl` I could help you to add it here too.
But a Common API would be nice between these packages.
